In [1]:
#importing np
import numpy as np

###### Question 1 : Write a code to combine one dimension and two dimensional NUMPY array

In [2]:
#Initialising 1D array:
list1=np.array(["a","b","c","d"])
print("1D Array=\n", list1, "\n")

#Initialising 2D array:
list2=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D Array=\n", list2, "\n")

list3=np.append(list2, list1)
print("1D array and 2D array combined= \n", list3)

1D Array=
 ['a' 'b' 'c' 'd'] 

2D Array=
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

1D array and 2D array combined= 
 ['1' '2' '3' '4' '5' '6' '7' '8' '9' 'a' 'b' 'c' 'd']


##### Question 2: Write a code to check whether a numpy array contains a specific row.



###### I dont know how to do this one, still I figured out two 3 methods using if else and command arr.tolist()



In [14]:
#Method 1 :  If the requested list is available in the given array, it returns True and if not then False.

import numpy as np
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15],
                [16, 17, 18, 19, 20]])

# view array
print(arr)
  
# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())            #using command arr.tolist()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True


In [3]:
#Method 2 :  how to find a specific 'element' of given array
#if the element is found, it returns True else it returns False


arr1=np.array([[1,2], [3,4], [5,6]])
print(arr1)

x = int(input())
row=x

if row in arr1:
    print("Yes",x,"is present in the given array")
else:
    print("No",x,"is not present in the given array")

[[1 2]
 [3 4]
 [5 6]]
2
Yes 2 is present in the given array


In [4]:
#Method 3 : 
# We will use an if else statement here also, but here we search for directly the row number.

#Applying this method on a 2D array

arr2=np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(arr2)

dim=arr2.ndim        #2
size=arr2.size       #10

x=int(input())  #taking input

numofrows=size/dim

if (x<numofrows):
    print("Yes, Row number", x, "is present in the given array")
else:
    print("No, Row number", x, "is not present in the given array")

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2
Yes, Row number 2 is present in the given array


In [5]:
#Applying the same to a 3D Array:

ar2=np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(ar2)

dim=ar2.ndim        #3
size=ar2.size       #12

x=int(input())  #taking input

numofrows=size/dim

if (x<numofrows):
    print("Yes, Row number", x, "is present in the given array")
else:
    print("No, Row number", x, "is not present in the given array")

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
2
Yes, Row number 2 is present in the given array


###### Question 3: Write a pandas code to create and display a DataFrame from a specified dictionary data which has the index labels

In [6]:
 #importing pandas library
import pandas as pd

In [7]:
#creating a dictionary
dic={'Time':[100, 0, 100],'Money':[0,100,100],'Energy':[100,100,0]}
     

#Creating DataFrame and putting index labels
datf=pd.DataFrame(dic, index=["Toddler", "Teenager", "Elderly"])
print("Rule of life:\n")
print(datf, "\n \n \n")

#Finding a specific row using index label:
print("Finding the data of row 'Toddler': \n")
print(datf.loc["Toddler"])

Rule of life:

          Time  Money  Energy
Toddler    100      0     100
Teenager     0    100     100
Elderly    100    100       0 
 
 

Finding the data of row 'Toddler': 

Time      100
Money       0
Energy    100
Name: Toddler, dtype: int64


###### Question 4: Write a pandas code to create DataFrame from dictionary of narray/lists

In [8]:
#Creating a dictionary of lists:
MoonKnightDictionary={
       'Name':['Steven', 'Mark', 'Jake'], 
       'Age':[44,44,44], 
       'Net Worth':['10M','271B','126M']
      }

MoonKnightDataFrame=pd.DataFrame(MoonKnightDictionary)
print(MoonKnightDataFrame)

     Name  Age Net Worth
0  Steven   44       10M
1    Mark   44      271B
2    Jake   44      126M


###### Question 5: Write a pandas code to create pandas DataFrame using list of lists

In [16]:
#Creating a list of lists:

List=[ 
["a","b","c", True],
["d","e","f", True],
["g","h","i", True],
["x","p","z", False]]

#initiating DataFrame

L1_df=pd.DataFrame(List)
print(L1_df)

   0  1  2      3
0  a  b  c   True
1  d  e  f   True
2  g  h  i   True
3  x  p  z  False
